[#38] Fix : cicd.yaml 재수정

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -37,7 +37,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Set target environment
-        run: | # 이 줄이 들여쓰기 문제로 인해 작동하지 않았음
+        run: |
           STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.HOST }}/api/env")
           if [ $STATUS -eq 200 ]; then
             CURRENT_ENV=$(curl -s "http://${{ secrets.HOST }}/api/env")
@@ -73,3 +73,87 @@ jobs:
           script: |
             sudo sed -i "s/set \$service_url .*;/set \$service_url ${{ env.TARGET_ENV }};/g" /etc/nginx/conf.d/service-env.inc
             sudo nginx -s reload
+
+      - name: Set target IP (MAIN)
+        run: |
+          STATUS=$(curl -o /dev/null -w "%{http_code}" "https://${{ secrets.MAIN_NGINX_EC2_DOMAIN }}/api/env")
+          if [ $STATUS -eq 200 ]; then
+            CURRENT_UPSTREAM=$(curl -s "https://${{ secrets.MAIN_NGINX_EC2_DOMAIN }}/api/env")
+          else
+            CURRENT_UPSTREAM=green
+          fi
+          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+          if [ $CURRENT_UPSTREAM = blue ]; then
+            echo "CURRENT_PORT1=3000" >> $GITHUB_ENV
+            echo "STOPPED_PORT1=3001" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAM = green ]; then
+            echo "CURRENT_PORT1=3001" >> $GITHUB_ENV
+            echo "STOPPED_PORT1=3000" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
+
+      - name: Docker compose (MAIN) - Primary Host
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.HOST }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script: |
+            cd server
+            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/puzzle:latest
+            sudo docker-compose -f docker-compose-${{ env.TARGET_UPSTREAM }}.yml up -d
+
+      - name: Docker compose (MAIN) - Secondary Host
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.HOST2 }}
+          key: ${{ secrets.EC2_SSH_KEY_2 }}
+          script_stop: true
+          script: |
+            cd server
+            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/puzzle:latest
+            sudo docker-compose -f docker-compose-${{ env.TARGET_UPSTREAM }}.yml up -d
+
+      - name: Check deploy server URL (MAIN)
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ secrets.HOST }}:${{ env.STOPPED_PORT1 }}/api/env
+          max-attempts: 5
+          retry-delay: 10s
+
+      - name: Change nginx upstream (MAIN)
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.HOST }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script: |
+            sudo docker exec -i nginxServer bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload'
+
+      - name: Stop current server (MAIN) - Primary Host
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.HOST }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script: |
+            sudo docker stop ${{ env.CURRENT_UPSTREAM }}
+            sudo docker rm ${{ env.CURRENT_UPSTREAM }}
+
+      - name: Stop current server (MAIN) - Secondary Host
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.HOST2 }}
+          key: ${{ secrets.EC2_SSH_KEY_2 }}
+          script_stop: true
+          script: |
+            sudo docker stop ${{ env.CURRENT_UPSTREAM }}
+            sudo docker rm ${{ env.CURRENT_UPSTREAM }}
